//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = module.exports = {};
var DelegatorUnbondingDelegation = module.exports.DelegatorUnbondingDelegation = function(args) {
  this.tokens = null;
  this.minTime = null;
  if (args) {
    if (args.tokens !== undefined && args.tokens !== null) {
      this.tokens = args.tokens;
    }
    if (args.minTime !== undefined && args.minTime !== null) {
      this.minTime = args.minTime;
    }
  }
};
DelegatorUnbondingDelegation.prototype = {};
DelegatorUnbondingDelegation.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.DOUBLE) {
        this.tokens = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.minTime = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DelegatorUnbondingDelegation.prototype.write = function(output) {
  output.writeStructBegin('DelegatorUnbondingDelegation');
  if (this.tokens !== null && this.tokens !== undefined) {
    output.writeFieldBegin('tokens', Thrift.Type.DOUBLE, 1);
    output.writeDouble(this.tokens);
    output.writeFieldEnd();
  }
  if (this.minTime !== null && this.minTime !== undefined) {
    output.writeFieldBegin('minTime', Thrift.Type.STRING, 2);
    output.writeString(this.minTime);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Delegator = module.exports.Delegator = function(args) {
  this.address = null;
    this.valAddress = null;
  this.shares = null;
  this.bondedTokens = null;
  this.unbondingDelegation = null;
  if (args) {
    if (args.address !== undefined && args.address !== null) {
      this.address = args.address;
    }
      if (args.valAddress !== undefined && args.valAddress !== null) {
          this.valAddress = args.valAddress;
    }
    if (args.shares !== undefined && args.shares !== null) {
      this.shares = args.shares;
    }
    if (args.bondedTokens !== undefined && args.bondedTokens !== null) {
      this.bondedTokens = args.bondedTokens;
    }
    if (args.unbondingDelegation !== undefined && args.unbondingDelegation !== null) {
      this.unbondingDelegation = new ttypes.DelegatorUnbondingDelegation(args.unbondingDelegation);
    }
  }
};
Delegator.prototype = {};
Delegator.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.address = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
          this.valAddress = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.DOUBLE) {
        this.shares = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.DOUBLE) {
        this.bondedTokens = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRUCT) {
        this.unbondingDelegation = new ttypes.DelegatorUnbondingDelegation();
        this.unbondingDelegation.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Delegator.prototype.write = function(output) {
  output.writeStructBegin('Delegator');
  if (this.address !== null && this.address !== undefined) {
    output.writeFieldBegin('address', Thrift.Type.STRING, 1);
    output.writeString(this.address);
    output.writeFieldEnd();
  }
    if (this.valAddress !== null && this.valAddress !== undefined) {
        output.writeFieldBegin('valAddress', Thrift.Type.STRING, 2);
        output.writeString(this.valAddress);
    output.writeFieldEnd();
  }
  if (this.shares !== null && this.shares !== undefined) {
    output.writeFieldBegin('shares', Thrift.Type.DOUBLE, 3);
    output.writeDouble(this.shares);
    output.writeFieldEnd();
  }
  if (this.bondedTokens !== null && this.bondedTokens !== undefined) {
    output.writeFieldBegin('bondedTokens', Thrift.Type.DOUBLE, 4);
    output.writeDouble(this.bondedTokens);
    output.writeFieldEnd();
  }
  if (this.unbondingDelegation !== null && this.unbondingDelegation !== undefined) {
    output.writeFieldBegin('unbondingDelegation', Thrift.Type.STRUCT, 5);
    this.unbondingDelegation.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CandidateDescription = module.exports.CandidateDescription = function(args) {
  this.details = null;
  this.identity = null;
  this.moniker = null;
  this.website = null;
  if (args) {
    if (args.details !== undefined && args.details !== null) {
      this.details = args.details;
    }
    if (args.identity !== undefined && args.identity !== null) {
      this.identity = args.identity;
    }
    if (args.moniker !== undefined && args.moniker !== null) {
      this.moniker = args.moniker;
    }
    if (args.website !== undefined && args.website !== null) {
      this.website = args.website;
    }
  }
};
CandidateDescription.prototype = {};
CandidateDescription.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.details = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.identity = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.moniker = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.website = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CandidateDescription.prototype.write = function(output) {
  output.writeStructBegin('CandidateDescription');
  if (this.details !== null && this.details !== undefined) {
    output.writeFieldBegin('details', Thrift.Type.STRING, 1);
    output.writeString(this.details);
    output.writeFieldEnd();
  }
  if (this.identity !== null && this.identity !== undefined) {
    output.writeFieldBegin('identity', Thrift.Type.STRING, 2);
    output.writeString(this.identity);
    output.writeFieldEnd();
  }
  if (this.moniker !== null && this.moniker !== undefined) {
    output.writeFieldBegin('moniker', Thrift.Type.STRING, 3);
    output.writeString(this.moniker);
    output.writeFieldEnd();
  }
  if (this.website !== null && this.website !== undefined) {
    output.writeFieldBegin('website', Thrift.Type.STRING, 4);
    output.writeString(this.website);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Candidate = module.exports.Candidate = function(args) {
  this.address = null;
  this.pubKey = null;
  this.shares = null;
  this.votingPower = null;
  this.description = null;
  this.delegators = null;
    this.upTime = null;
  if (args) {
    if (args.address !== undefined && args.address !== null) {
      this.address = args.address;
    }
    if (args.pubKey !== undefined && args.pubKey !== null) {
      this.pubKey = args.pubKey;
    }
    if (args.shares !== undefined && args.shares !== null) {
      this.shares = args.shares;
    }
    if (args.votingPower !== undefined && args.votingPower !== null) {
      this.votingPower = args.votingPower;
    }
    if (args.description !== undefined && args.description !== null) {
      this.description = new ttypes.CandidateDescription(args.description);
    }
    if (args.delegators !== undefined && args.delegators !== null) {
      this.delegators = Thrift.copyList(args.delegators, [ttypes.Delegator]);
    }
      if (args.upTime !== undefined && args.upTime !== null) {
          this.upTime = args.upTime;
      }
  }
};
Candidate.prototype = {};
Candidate.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.address = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.pubKey = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.DOUBLE) {
        this.shares = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.DOUBLE) {
        this.votingPower = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRUCT) {
        this.description = new ttypes.CandidateDescription();
        this.description.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.delegators = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = new ttypes.Delegator();
          elem6.read(input);
          this.delegators.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
          break;
        case 7:
            if (ftype == Thrift.Type.DOUBLE) {
                this.upTime = input.readDouble();
            } else {
                input.skip(ftype);
            }
            break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Candidate.prototype.write = function(output) {
  output.writeStructBegin('Candidate');
  if (this.address !== null && this.address !== undefined) {
    output.writeFieldBegin('address', Thrift.Type.STRING, 1);
    output.writeString(this.address);
    output.writeFieldEnd();
  }
  if (this.pubKey !== null && this.pubKey !== undefined) {
    output.writeFieldBegin('pubKey', Thrift.Type.STRING, 2);
    output.writeString(this.pubKey);
    output.writeFieldEnd();
  }
  if (this.shares !== null && this.shares !== undefined) {
    output.writeFieldBegin('shares', Thrift.Type.DOUBLE, 3);
    output.writeDouble(this.shares);
    output.writeFieldEnd();
  }
  if (this.votingPower !== null && this.votingPower !== undefined) {
    output.writeFieldBegin('votingPower', Thrift.Type.DOUBLE, 4);
    output.writeDouble(this.votingPower);
    output.writeFieldEnd();
  }
  if (this.description !== null && this.description !== undefined) {
    output.writeFieldBegin('description', Thrift.Type.STRUCT, 5);
    this.description.write(output);
    output.writeFieldEnd();
  }
  if (this.delegators !== null && this.delegators !== undefined) {
    output.writeFieldBegin('delegators', Thrift.Type.LIST, 6);
    output.writeListBegin(Thrift.Type.STRUCT, this.delegators.length);
    for (var iter7 in this.delegators)
    {
      if (this.delegators.hasOwnProperty(iter7))
      {
        iter7 = this.delegators[iter7];
        iter7.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
    if (this.upTime !== null && this.upTime !== undefined) {
        output.writeFieldBegin('upTime', Thrift.Type.DOUBLE, 7);
        output.writeDouble(this.upTime);
        output.writeFieldEnd();
    }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Exception = module.exports.Exception = function(args) {
  Thrift.TException.call(this, "Exception");
  this.name = "Exception";
  this.errCode = null;
  this.errMsg = null;
  if (args) {
    if (args.errCode !== undefined && args.errCode !== null) {
      this.errCode = args.errCode;
    }
    if (args.errMsg !== undefined && args.errMsg !== null) {
      this.errMsg = args.errMsg;
    }
  }
};
Thrift.inherits(Exception, Thrift.TException);
Exception.prototype.name = 'Exception';
Exception.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.errCode = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.errMsg = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Exception.prototype.write = function(output) {
  output.writeStructBegin('Exception');
  if (this.errCode !== null && this.errCode !== undefined) {
    output.writeFieldBegin('errCode', Thrift.Type.I32, 1);
    output.writeI32(this.errCode);
    output.writeFieldEnd();
  }
  if (this.errMsg !== null && this.errMsg !== undefined) {
    output.writeFieldBegin('errMsg', Thrift.Type.STRING, 2);
    output.writeString(this.errMsg);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CandidateListRequest = module.exports.CandidateListRequest = function(args) {
  this.address = null;
  this.page = null;
  this.perPage = null;
  this.sort = null;
  this.q = null;
  if (args) {
    if (args.address !== undefined && args.address !== null) {
      this.address = args.address;
    }
    if (args.page !== undefined && args.page !== null) {
      this.page = args.page;
    }
    if (args.perPage !== undefined && args.perPage !== null) {
      this.perPage = args.perPage;
    }
    if (args.sort !== undefined && args.sort !== null) {
      this.sort = args.sort;
    }
    if (args.q !== undefined && args.q !== null) {
      this.q = args.q;
    }
  }
};
CandidateListRequest.prototype = {};
CandidateListRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.address = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I16) {
        this.page = input.readI16();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I16) {
        this.perPage = input.readI16();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.sort = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.q = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CandidateListRequest.prototype.write = function(output) {
  output.writeStructBegin('CandidateListRequest');
  if (this.address !== null && this.address !== undefined) {
    output.writeFieldBegin('address', Thrift.Type.STRING, 1);
    output.writeString(this.address);
    output.writeFieldEnd();
  }
  if (this.page !== null && this.page !== undefined) {
    output.writeFieldBegin('page', Thrift.Type.I16, 2);
    output.writeI16(this.page);
    output.writeFieldEnd();
  }
  if (this.perPage !== null && this.perPage !== undefined) {
    output.writeFieldBegin('perPage', Thrift.Type.I16, 3);
    output.writeI16(this.perPage);
    output.writeFieldEnd();
  }
  if (this.sort !== null && this.sort !== undefined) {
    output.writeFieldBegin('sort', Thrift.Type.STRING, 4);
    output.writeString(this.sort);
    output.writeFieldEnd();
  }
  if (this.q !== null && this.q !== undefined) {
    output.writeFieldBegin('q', Thrift.Type.STRING, 5);
    output.writeString(this.q);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CandidateDetailRequest = module.exports.CandidateDetailRequest = function(args) {
    this.delAddress = null;
    this.valAddress = null;
  if (args) {
      if (args.delAddress !== undefined && args.delAddress !== null) {
          this.delAddress = args.delAddress;
    }
      if (args.valAddress !== undefined && args.valAddress !== null) {
          this.valAddress = args.valAddress;
    }
  }
};
CandidateDetailRequest.prototype = {};
CandidateDetailRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
          this.delAddress = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
          this.valAddress = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CandidateDetailRequest.prototype.write = function(output) {
  output.writeStructBegin('CandidateDetailRequest');
    if (this.delAddress !== null && this.delAddress !== undefined) {
        output.writeFieldBegin('delAddress', Thrift.Type.STRING, 1);
        output.writeString(this.delAddress);
    output.writeFieldEnd();
  }
    if (this.valAddress !== null && this.valAddress !== undefined) {
        output.writeFieldBegin('valAddress', Thrift.Type.STRING, 2);
        output.writeString(this.valAddress);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var DelegatorCandidateListRequest = module.exports.DelegatorCandidateListRequest = function(args) {
  this.address = null;
  this.page = null;
  this.perPage = null;
  this.sort = null;
  this.q = null;
  if (args) {
    if (args.address !== undefined && args.address !== null) {
      this.address = args.address;
    }
    if (args.page !== undefined && args.page !== null) {
      this.page = args.page;
    }
    if (args.perPage !== undefined && args.perPage !== null) {
      this.perPage = args.perPage;
    }
    if (args.sort !== undefined && args.sort !== null) {
      this.sort = args.sort;
    }
    if (args.q !== undefined && args.q !== null) {
      this.q = args.q;
    }
  }
};
DelegatorCandidateListRequest.prototype = {};
DelegatorCandidateListRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.address = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I16) {
        this.page = input.readI16();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I16) {
        this.perPage = input.readI16();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.sort = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.q = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DelegatorCandidateListRequest.prototype.write = function(output) {
  output.writeStructBegin('DelegatorCandidateListRequest');
  if (this.address !== null && this.address !== undefined) {
    output.writeFieldBegin('address', Thrift.Type.STRING, 1);
    output.writeString(this.address);
    output.writeFieldEnd();
  }
  if (this.page !== null && this.page !== undefined) {
    output.writeFieldBegin('page', Thrift.Type.I16, 2);
    output.writeI16(this.page);
    output.writeFieldEnd();
  }
  if (this.perPage !== null && this.perPage !== undefined) {
    output.writeFieldBegin('perPage', Thrift.Type.I16, 3);
    output.writeI16(this.perPage);
    output.writeFieldEnd();
  }
  if (this.sort !== null && this.sort !== undefined) {
    output.writeFieldBegin('sort', Thrift.Type.STRING, 4);
    output.writeString(this.sort);
    output.writeFieldEnd();
  }
  if (this.q !== null && this.q !== undefined) {
    output.writeFieldBegin('q', Thrift.Type.STRING, 5);
    output.writeString(this.q);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TotalShareRequest = module.exports.TotalShareRequest = function(args) {
  this.address = null;
  if (args) {
    if (args.address !== undefined && args.address !== null) {
      this.address = args.address;
    }
  }
};
TotalShareRequest.prototype = {};
TotalShareRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.address = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TotalShareRequest.prototype.write = function(output) {
  output.writeStructBegin('TotalShareRequest');
  if (this.address !== null && this.address !== undefined) {
    output.writeFieldBegin('address', Thrift.Type.STRING, 1);
    output.writeString(this.address);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TotalShareResponse = module.exports.TotalShareResponse = function(args) {
  this.totalShares = null;
  this.bondedTokens = null;
  this.unbondingTokens = null;
  if (args) {
    if (args.totalShares !== undefined && args.totalShares !== null) {
      this.totalShares = args.totalShares;
    }
    if (args.bondedTokens !== undefined && args.bondedTokens !== null) {
      this.bondedTokens = args.bondedTokens;
    }
    if (args.unbondingTokens !== undefined && args.unbondingTokens !== null) {
      this.unbondingTokens = args.unbondingTokens;
    }
  }
};
TotalShareResponse.prototype = {};
TotalShareResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.DOUBLE) {
        this.totalShares = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.DOUBLE) {
        this.bondedTokens = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.DOUBLE) {
        this.unbondingTokens = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TotalShareResponse.prototype.write = function(output) {
  output.writeStructBegin('TotalShareResponse');
  if (this.totalShares !== null && this.totalShares !== undefined) {
    output.writeFieldBegin('totalShares', Thrift.Type.DOUBLE, 1);
    output.writeDouble(this.totalShares);
    output.writeFieldEnd();
  }
  if (this.bondedTokens !== null && this.bondedTokens !== undefined) {
    output.writeFieldBegin('bondedTokens', Thrift.Type.DOUBLE, 2);
    output.writeDouble(this.bondedTokens);
    output.writeFieldEnd();
  }
  if (this.unbondingTokens !== null && this.unbondingTokens !== undefined) {
    output.writeFieldBegin('unbondingTokens', Thrift.Type.DOUBLE, 3);
    output.writeDouble(this.unbondingTokens);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ValidatorExRateRequest = module.exports.ValidatorExRateRequest = function(args) {
  this.validatorAddress = null;
  if (args) {
    if (args.validatorAddress !== undefined && args.validatorAddress !== null) {
      this.validatorAddress = args.validatorAddress;
    }
  }
};
ValidatorExRateRequest.prototype = {};
ValidatorExRateRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.validatorAddress = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ValidatorExRateRequest.prototype.write = function(output) {
  output.writeStructBegin('ValidatorExRateRequest');
  if (this.validatorAddress !== null && this.validatorAddress !== undefined) {
    output.writeFieldBegin('validatorAddress', Thrift.Type.STRING, 1);
    output.writeString(this.validatorAddress);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ValidatorExRateResponse = module.exports.ValidatorExRateResponse = function(args) {
  this.tokenSharesRate = null;
  if (args) {
    if (args.tokenSharesRate !== undefined && args.tokenSharesRate !== null) {
      this.tokenSharesRate = args.tokenSharesRate;
    }
  }
};
ValidatorExRateResponse.prototype = {};
ValidatorExRateResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.DOUBLE) {
        this.tokenSharesRate = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ValidatorExRateResponse.prototype.write = function(output) {
  output.writeStructBegin('ValidatorExRateResponse');
  if (this.tokenSharesRate !== null && this.tokenSharesRate !== undefined) {
    output.writeFieldBegin('tokenSharesRate', Thrift.Type.DOUBLE, 1);
    output.writeDouble(this.tokenSharesRate);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

